name: npm build, lint, test and publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t ishanjainijs/github-action-example-node .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.ReenaS@1909 }}
          DOCKER_USERNAME: ${{ secrets.jeysakthi7@gmail.com }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push jeysakthi/Gatling_sample
